"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var id_pb_1 = require("./id_pb");
exports.Id = id_pb_1.Id;
var example_pb_1 = require("./example_pb");
exports.Example = example_pb_1.Example;
var lang_item_pb_1 = require("./lang-item_pb");
exports.LangItem = lang_item_pb_1.LangItem;
var lang_item_service_grpc_pb_1 = require("./lang-item-service_grpc_pb");
exports.LangItemServiceService = lang_item_service_grpc_pb_1.LangItemServiceService;
exports.LangItemServiceClient = lang_item_service_grpc_pb_1.LangItemServiceClient;
