/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var example_pb = require('./example_pb.js');
goog.exportSymbol('proto.LangItem', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.LangItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.LangItem.repeatedFields_, null);
};
goog.inherits(proto.LangItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.LangItem.displayName = 'proto.LangItem';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.LangItem.repeatedFields_ = [4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.LangItem.prototype.toObject = function(opt_includeInstance) {
  return proto.LangItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.LangItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LangItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    chinese: jspb.Message.getFieldWithDefault(msg, 2, ""),
    pinyin: jspb.Message.getFieldWithDefault(msg, 3, ""),
    englishList: jspb.Message.getRepeatedField(msg, 4),
    examplesList: jspb.Message.toObjectList(msg.getExamplesList(),
    example_pb.Example.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.LangItem}
 */
proto.LangItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.LangItem;
  return proto.LangItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.LangItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.LangItem}
 */
proto.LangItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setChinese(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPinyin(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addEnglish(value);
      break;
    case 5:
      var value = new example_pb.Example;
      reader.readMessage(value,example_pb.Example.deserializeBinaryFromReader);
      msg.addExamples(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.LangItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.LangItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.LangItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LangItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getChinese();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPinyin();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getEnglishList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
  f = message.getExamplesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      example_pb.Example.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.LangItem.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.LangItem.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string chinese = 2;
 * @return {string}
 */
proto.LangItem.prototype.getChinese = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.LangItem.prototype.setChinese = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string pinyin = 3;
 * @return {string}
 */
proto.LangItem.prototype.getPinyin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.LangItem.prototype.setPinyin = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * repeated string english = 4;
 * @return {!Array.<string>}
 */
proto.LangItem.prototype.getEnglishList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/** @param {!Array.<string>} value */
proto.LangItem.prototype.setEnglishList = function(value) {
  jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.LangItem.prototype.addEnglish = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


proto.LangItem.prototype.clearEnglishList = function() {
  this.setEnglishList([]);
};


/**
 * repeated Example examples = 5;
 * @return {!Array.<!proto.Example>}
 */
proto.LangItem.prototype.getExamplesList = function() {
  return /** @type{!Array.<!proto.Example>} */ (
    jspb.Message.getRepeatedWrapperField(this, example_pb.Example, 5));
};


/** @param {!Array.<!proto.Example>} value */
proto.LangItem.prototype.setExamplesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.Example=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Example}
 */
proto.LangItem.prototype.addExamples = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.Example, opt_index);
};


proto.LangItem.prototype.clearExamplesList = function() {
  this.setExamplesList([]);
};


goog.object.extend(exports, proto);
