version: '3.7'

services:
  zodiac-lang-item:
    build: './lang-item/service'
    image: 'zodiac-lang-item'
    environment:
      - NODE_ENV=production
    ports:
      - '11000:11000'
    networks:
      - 'zodiac'
  zodiac-gateway:
    build: './gateway/service'
    image: 'zodiac-gateway'
    environment:
      - NODE_ENV=production
    depends_on:
      - 'zodiac-lang-item'
    ports:
      - '5000:5000'
    networks:
      - 'zodiac'
  zodiac-web:
    build: './web'
    image: 'zodiac-web'
    environment:
      - NODE_ENV=production
    ports:
      - '4200:4200'
    networks:
      - 'zodiac'

networks:
  zodiac:
