version: '3.7'

services:
  zodiac-deps:
    build: ./deps
    image: zodiac-deps
    ports:
      - 14873:4783
    networks:
      - public
  zodiac-lang-item:
    build: ./lang-item/service
    image: zodiac-lang-item
    environment:
      - NODE_ENV=production
    depends_on:
      - zodiac-deps
    networks:
      - public
  zodiac-gateway:
    build: ./gateway/service
    image: zodiac-gateway
    environment:
      - NODE_ENV=production
    depends_on:
      - zodiac-deps
      - zodiac-lang-item
    ports:
      - 5000:80
    networks:
      - public
  zodiac-web:
    build: ./web
    image: zodiac-web
    environment:
      - NODE_ENV=production
    depends_on:
      - zodiac-deps
    ports:
      - 8080:8080
    networks:
      - public

networks:
  public:
