version: '3'

services:
  zodiac-lang-item:
    build: './lang-item/service'
    image: 'zodiac-lang-item'
    volumes:
      - ./lang-item/service/src:/app/src
    ports:
      - '11000:11000'
    networks:
      - 'zodiac'
  zodiac-gateway:
    build: './gateway/service'
    image: 'zodiac-gateway'
    volumes:
      - ./gateway/service/src:/app/src
    depends_on:
      - 'zodiac-lang-item'
    ports:
      - '5000:5000'
    networks:
      - 'zodiac'

networks:
  zodiac:
